name: Extracting VerCode - JP

on:
  push:
    branches: [JP]
  pull_request:
    branches: [JP]
  schedule:
    - cron: "15 19 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Install Requeriments
        run: pip install -r https://raw.githubusercontent.com/O-Isaac/FGO-VerCode/JP/requirements.txt

      - name: Gettings files from Repo
        uses: actions/checkout@v2

      - name: Execute main script
        run: python3 main.py

      - name: Commit & push changes to branch NA
        uses: actions-js/push@master
        with:
          force: true
          branch: "JP"
          github_token: ${{ secrets.TOKEN_REPO }}
